config/routes.rb
Rails.application.routes.draw do
  root 'tops#index'

  resource :tops, only: [] do
    collection do
      get 'terms_of_service'
      get 'privacy_policy'
    end
  end

  resource :users, only: %i[new create show edit update]

  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'

  post "oauth/callback", to: "oauths#callback"
  get "oauth/callback", to: "oauths#callback"
  get "oauth/:provider", to: "oauths#oauth", as: :auth_at_provider

  resource :my_page, only: [] do
    collection do
      get 'home', as: ''
      get 'liked'
      get 'my_posts'
    end
  end

  resources :password_resets, only: %i[ new create edit update ] do
    collection do
      get 'sended_mail'
      get 'after_setting'
    end
  end

  resources :posts do
    resource :likes, only: %i[ create destroy ]
    resources :likes, only: %i[ index ]
    resources :comments
    collection do
      get 'ranking'
      get 'rakuten_search'
    end
  end

  resources :gadgets do
    collection do
      get 'ranking'
    end
  end

  resources :autocomplete do
    collection do
      get :brand
      get :name
    end
  end

  resources :my_desks do
    member do
      post 'add_gadget'
      delete 'remove_gadget'
    end
  end

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :content, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post, only: %i[new edit create update destroy]
  before_action :set_comment, only: %i[edit update destroy]

  def new
    @comment = current_user.comments.new(post_id: @post.id)
  end

  def edit
  end

  def create
    @comment = current_user.comments.new(comment_params)
    respond_to do |format|
      if @comment.save
        format.turbo_stream
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.turbo_stream
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @comment.destroy!
    respond_to do |format|
      format.turbo_stream
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:content).merge(post_id: @post.id)
  end

  def set_post
    @post = Post.find(params[:post_id])
  end

  def set_comment
    @comment = Comment.find(params[:id])
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
  def my_comment?(comment_user_id)
    current_user.id == comment_user_id
  end
end

app/views/comments/_comment.html.erb
<%= turbo_frame_tag dom_id(comment, :edit) do %>
  <div id="<%= dom_id(comment) %>" class="border rounded my-2">
    <div class="flex justify-between items-center py-2 bg-slate-100">
      <p class="pl-2">
        <%= comment.user.name %>
      </p>
      <% if my_comment?(comment.user.id) %>
        <div>
          <%= link_to edit_post_comment_path(comment.post, comment), data: { turbo_frame: dom_id(comment, :edit) }, class: "p-1 rounded-full hover:bg-slate-300 active:bg-slate-400" do %>
            <i class="fa-regular fa-pen-to-square"></i>
          <% end %>
          <%= link_to post_comment_path(comment.post, comment), data: { turbo_method: :delete, turbo_confirm: t('.delete_confirmation') }, class: "px-2 py-1 rounded-full hover:bg-slate-300 active:bg-slate-400" do %>
            <i class="fa-regular fa-trash-can"></i>
          <% end %>
        </div>
      <% end %>
    </div>
    <p class="p-2">
      <%= safe_join(comment.content.split("\n"),tag(:br)) %>
    </p>
    <p class="px-2 mt-3 text-sm text-end">
      <%= l(comment.created_at, format: :long) %>
    </p>
  </div>
<% end %>

app/views/comments/_form.html.erb
<%= form_with model: [@post, @comment], local: false do |f| %>
  <%= render 'shared/error_message', object: f.object %>
    <div class="flex justify-between items-center py-2 rounded-t-lg border-x border-t bg-slate-100">
      <p class="pl-2">
        <%= current_user.name %>
      </p>
      <div class="flex gap-2">
        <%= f.submit class: "border rounded-lg p-1 bg-gray-800 hover:bg-gray-600 active:bg-gray-500 text-sm text-white cursor-pointer font-semibold" %>
        <%= link_to '#', class: "text-xl mr-3 px-2 rounded-full hover:bg-slate-300" do%>
          <i class="fa-solid fa-xmark"></i>
        <% end %>
      </div>
    </div>
    <%= f.text_area :content, class: "base-form-area text-base w-full h-full" %>
<% end %>

app/views/comments/create.turbo_stream.erb
<%= turbo_stream.append 'comments', partial: 'comments/comment', locals: { comment: @comment } %>
<%= turbo_stream.update Comment.new, "" %>

app/views/comments/destroy.turbo_stream.erb
<%= turbo_stream.remove dom_id(@comment) %>

app/views/comments/edit.html.erb
<%= turbo_frame_tag dom_id(@comment, :edit) do %>
  <%= render 'form' %>
<% end %>

app/views/comments/new.html.erb
<%= turbo_frame_tag "new_comment" do %>
  <%= render 'form' %>
<% end %>

app/views/comments/update.turbo_stream.erb
<%= turbo_stream.replace dom_id(@comment, :edit), partial: 'comments/comment', locals: { comment: @comment } %>