config/routes.rb
Rails.application.routes.draw do
  root 'tops#index'

  resource :tops, only: [] do
    collection do
      get 'terms_of_service'
      get 'privacy_policy'
    end
  end

  resource :users, only: %i[new create show edit update]

  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'

  post "oauth/callback", to: "oauths#callback"
  get "oauth/callback", to: "oauths#callback"
  get "oauth/:provider", to: "oauths#oauth", as: :auth_at_provider

  resource :my_page, only: [] do
    collection do
      get 'home', as: ''
      get 'liked'
      get 'my_posts'
    end
  end

  resources :password_resets, only: %i[ new create edit update ] do
    collection do
      get 'sended_mail'
      get 'after_setting'
    end
  end

  resources :posts do
    resource :likes, only: %i[ create destroy ]
    resources :likes, only: %i[ index ]
    resources :comments
    collection do
      get 'ranking'
      get 'rakuten_search'
    end
  end

  resources :gadgets do
    collection do
      get 'ranking'
    end
  end

  resources :autocomplete do
    collection do
      get :brand
      get :name
    end
  end

  resources :my_desks do
    member do
      post 'add_gadget'
      delete 'remove_gadget'
    end
  end

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!
  has_many :authentications, dependent: :destroy
  accepts_nested_attributes_for :authentications

  has_many :posts, dependent: :destroy
  has_many :my_desks, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :post
  has_many :comments, dependent: :destroy

  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }
  validates :reset_password_token, presence: true, uniqueness: true, allow_nil: true

  validates :email, uniqueness: true, presence: true
  validates :name, presence: true
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: %i[new create]
  before_action :set_user, only: %i[edit update]

  def show
    current_user
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)
    if @user.save
      auto_login(@user)
      @user.my_desks.create!(name: 'Default')
      redirect_to root_path, flash: { success: t('.success') }
    else
      flash.now[:error] = t('.error')
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @user.update(user_params)
      respond_to do |format|
        format.html { redirect_to user_path(@user) }
        flash.now[:success] = t('.update')
        format.turbo_stream
      end
    else
      respond_to do |format|
        format.html { render :edit, status: :unprocessable_entity }
        format.turbo_stream { @user }
      end
    end
  end

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :salt, :name)
  end

  def set_user
    @user = User.find(current_user.id)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def logged_in_for_x?
    current_user.x_id.present?
  end
end

app/views/users/_after_email.html.erb
<%= turbo_frame_tag 'user-email' do %>
  <% render 'email_content', user: user %>
<% end %>

app/views/users/_after_name.html.erb
<%= turbo_frame_tag 'user-name' do %>
  <% render 'name_content', user: user %>
<% end %>

app/views/users/_email_content.html.erb
<div class="flex my-4 w-auto justify-between">
  <p class="my-1">
    <i class="fa-solid fa-envelope pr-3"></i>
    <%= User.human_attribute_name :email %>
  </p>
  <% unless logged_in_for_x? %>
    <%= link_to t('defaults.change'), edit_users_path, class: "base-btn", data: { turbo_frame: 'user-email' } %>
  <% end %>
</div>
<p class="w-full text-center border rounded py-2 px-3 bg-white"><%= user.email %></p>

app/views/users/_name_content.html.erb
<div class="flex my-3 w-auto justify-between">
  <p class="my-1">
    <i class="fa-solid fa-user pr-3"></i>
    <%= User.human_attribute_name :name %>
  </p>
  <% unless logged_in_for_x? %>
    <%= link_to t('defaults.change'), edit_users_path, class: "base-btn", data: { turbo_frame: 'user-name' } %>
  <% end %>
</div>
<p class="w-full text-center border rounded py-2 px-3 bg-white"><%= user.name %></p>

app/views/users/edit.html.erb
<%= turbo_frame_tag 'user-name' do %>
  <%= form_with model:@user, url: users_path, method: :put do |f|%>
    <div class="flex my-4 w-auto justify-between">
      <p class="my-1">
        <i class="fa-solid fa-user pr-3"></i>
        <%= User.human_attribute_name :name %>
      </p>
      <div class="flex">
        <%= f.submit class: "base-btn" %>
        <%= link_to t('defaults.cancel'), users_path, class: "cancel-btn ml-1" %>
      </div>
    </div>
    <%= f.text_field :name, value: current_user.name, class: 'base-form-area w-full text-center' %>
  <% end %>
<% end %>

<%= turbo_frame_tag 'user-email' do %>
  <%= form_with model:@user, url: users_path, method: :put do |f|%>
    <div class="flex my-4 w-auto justify-between">
      <p class="my-1">
        <i class="fa-solid fa-envelope pr-3"></i>
        <%= User.human_attribute_name :email %>
      </p>
      <div class="flex">
        <%= f.submit class: "base-btn" %>
        <%= link_to t('defaults.cancel'), users_path, class: "cancel-btn ml-1" %>
      </div>
    </div>
    <%= f.text_field :email, value: current_user.email, class: 'base-form-area w-full text-center' %>
  <% end %>
<% end %>

app/views/users/new.html.erb
<% set_meta_tags title: t('.title') %>
<div class="flex justify-center my-10 md:my-5 h-full">
  <div class="bg-white w-4/4 md:w-2/3 p-5 border rounded-xl text-base md:text-lg">
    <h1 class="text-center m-6 text-xl md:text-2xl font-bold"><i class="fa-solid fa-user-plus mr-2"></i><%= t('.title') %></h1>
    <div class="flex justify-center">
      <%= form_with model: @user, local: true do |f| %>
        <%= render 'shared/error_message', object: f.object %>
        <div class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name, class: 'form-control base-form-area w-full max-w-xs', size: "50" %>
        </div>
        <div class="form-group mt-3">
          <%= f.label :email %>
          <%= f.email_field :email, class: 'form-control base-form-area w-full max-w-xs' %>
        </div>
        <div class="form-group mt-3">
          <%= f.label :password %>
          <%= f.password_field :password, class: 'form-control base-form-area w-full max-w-xs' %>
        </div>
        <div class="form-group mt-3">
          <%= f.label :password_confirmation %>
          <%= f.password_field :password_confirmation, class: 'form-control base-form-area w-full max-w-xs' %>
        </div>
        <div class="flex justify-center">
          <%= f.submit t('defaults.sign_up'), class: 'base-btn w-2/4 mt-8' %>
        </div>
      <% end %>
    </div>

    <div class="flex items-center justify-center space-x-2 my-5">
      <div class="flex-1 md:flex-none md:w-1/5 h-0.5 bg-slate-200"></div>
      <span class="px-2">or</span>
      <div class="flex-1 md:flex-none md:w-1/5 h-0.5 bg-slate-200"></div>
    </div>

    <div class="flex justify-center">
      <%= link_to t('.x_login'), auth_at_provider_path(provider: :twitter), class: "base-btn"%>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<%= turbo_frame_tag "content" do %>
  <div id="error_message"></div>
  <div class="flex flex-col justify-center">
    <% if logged_in_for_x? %>
      <p class="p-1 bg-blue-100 text-blue-500 font-medium rounded-lg border w-52 text-center">
        <%= t('.x_login_now') %>
      </p>
    <% end %>
    <div class="flex flex-col w-auto">
      <%= turbo_frame_tag 'user-name' do %>
        <% render 'name_content', user: current_user %>
      <% end %>
    </div>
    <div class="flex flex-col w-auto">
      <%= turbo_frame_tag 'user-email' do %>
        <%  render 'email_content', user: current_user %>
      <% end %>
    </div>
    <% unless logged_in_for_x? %>
      <div class="flex flex-col w-auto">
        <div class="flex my-4 w-auto justify-between">
          <p class="my-1">
            <i class="fa-solid fa-key pr-3"></i>
            <%= User.human_attribute_name :password %>
          </p>
        </div>
        <p class="w-full text-center border rounded py-2 px-3 bg-white">●●●●●●●●●●</p>
        <p class="text-center mt-4">
        <%= t('.changed_password') %>
        <%= link_to t('.this'), new_password_reset_path,  class: 'link link-primary', data: { turbo_frame: "_top" } %>
        <%= t('.changed_password2') %>
        </p>
      </div>
    <% else %>
      <div class="flex justify-center my-10">
        <p class="p-2 bg-red-100 text-red-500 font-medium rounded-lg border">
          <%= t('.x_user_announcement') %>
        </p>
      </div>
    <% end %>
  </div>
<% end %>

app/views/users/update.turbo_stream.erb
<% if @user.errors.any? %>
  <%= turbo_stream.update 'error_message', partial: 'shared/error_message', locals: { object: @user } %>
<% else %>
  <%= turbo_stream.update 'error_message', '' %>
  <%= turbo_stream.update 'flash_messages', partial: 'shared/flash_message', locals: { flash: flash } %>
  <%= turbo_stream.replace 'user-name', partial: 'users/after_name', locals: { user: @user } %>
  <%= turbo_stream.replace 'user-email', partial: 'users/after_email', locals: { user: @user } %>
<% end %>