config/routes.rb
Rails.application.routes.draw do
  root 'tops#index'

  resource :tops, only: [] do
    collection do
      get 'terms_of_service'
      get 'privacy_policy'
    end
  end

  resource :users, only: %i[new create show edit update]

  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'

  post "oauth/callback", to: "oauths#callback"
  get "oauth/callback", to: "oauths#callback"
  get "oauth/:provider", to: "oauths#oauth", as: :auth_at_provider

  resource :my_page, only: [] do
    collection do
      get 'home', as: ''
      get 'liked'
      get 'my_posts'
    end
  end

  resources :password_resets, only: %i[ new create edit update ] do
    collection do
      get 'sended_mail'
      get 'after_setting'
    end
  end

  resources :posts do
    resource :likes, only: %i[ create destroy ]
    resources :likes, only: %i[ index ]
    resources :comments
    collection do
      get 'ranking'
      get 'rakuten_search'
    end
  end

  resources :gadgets do
    collection do
      get 'ranking'
    end
  end

  resources :autocomplete do
    collection do
      get :brand
      get :name
    end
  end

  resources :my_desks do
    member do
      post 'add_gadget'
      delete 'remove_gadget'
    end
  end

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
end

app/views/shared/_error_message.html.erb
<%= turbo_frame_tag 'error_message' do %>
  <% if object.errors.any? %>
    <div id="error_messages" class="bg-red-100 text-lg text-red-700 px-5 py-3 mb-5 rounded-xl relative">
      <ul class="mb-0">
        <% object.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<% end %>

app/views/shared/_flash_message.html.erb
<%= turbo_frame_tag 'flash_messages' do %>
  <div data-controller="flash-message">
    <% flash.each do |message_type, message| %>
      <% if message_type == 'success' %>
        <div class="flex justify-center">
          <div role="alert" class="bg-green-200 text-green-700 py-3 px-8 rounded-lg fixed top-5 z-10" data-flash-message-target="message"><%= message %></div>
        </div>
      <% else %>
        <div class="flex justify-center">
          <div role="alert" class="bg-red-200 text-red-700 py-3 px-8 rounded-lg fixed top-5 z-10" data-flash-message-target="message"><%= message %></div>
        </div>
      <% end %>
    <% end %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer footer-center py-4 bg-slate-100 border-t shadow-inner">
  <nav class="flex gap-5">
    <%= link_to t('footer.terms_of_service'), terms_of_service_tops_path, class: "link link-hover" %>
    <%= link_to t('footer.privacy_policy'), privacy_policy_tops_path, class: "link link-hover" %>
    <%= link_to t('footer.contacts'), 'https://docs.google.com/forms/d/e/1FAIpQLSdcoluqNbg0c5PrSj22jBY5KUSUB9HnmZNekGE5nPq1vVUoTg/viewform?usp=sharing', target: :_blank, rel: "noopener noreferrer", class: "link link-hover" %>
  </nav>
</footer>

app/views/shared/_header.html.erb
<header class=" w-full flex items-center justify-between mx-auto bg-slate-100 border-b shadow">
  <%= link_to image_tag('top_page/header_logo.png', class: "h-10 mx-3"), login_user %>
  <%= render 'shared/menu' %>
</header>

app/views/shared/_menu.html.erb
<div class="drawer-end">
  <input id="my-drawer-4" type="checkbox" class="drawer-toggle">
  <div class="drawer-content">
    <label for="my-drawer-4" class="drawer-button btn bg-slate-100 border-none shadow-none"><i  class="fa-solid fa-bars fa-2xl"></i></label>
  </div>
  <div class="drawer-side z-50">
    <label for="my-drawer-4" aria-label="close sidebar" class="drawer-overlay"></label>
    <ul class="menu p-4 w-52 md:w-80 min-h-full bg-base-200 text-base-content">
      <% if logged_in? %>
        <li>
          <%= link_to my_page_path do%>
            <i class="fa-solid fa-user"></i>
            <%= t('menu.my_page') %>
          <% end %>
        <li>
        <li>
          <%= link_to new_post_path do %>
            <i class="fa-solid fa-pen-to-square"></i>
            <%= t('menu.new_post') %>
          <% end %>
        </li>
        <li>
          <%= link_to posts_path do %>
            <i class="fa-solid fa-desktop"></i>
            <%= t('menu.index') %>
          <% end %>
        </li>
        <li>
          <details open>
            <summary><i class="fa-solid fa-crown"></i><%= t('menu.ranking') %></summary>
            <ul>
              <li>
                <%= link_to ranking_posts_path do %>
                  <i class="fa-solid fa-ranking-star"></i>
                  <%= t('menu.post_ranking') %>
                <% end %>
              </li>
              <li>
                <%= link_to ranking_gadgets_path do %>
                  <i class="fa-regular fa-keyboard"></i>
                  <%= t('menu.gadget_ranking') %>
                <% end %>
              </li>
            </ul>
          </details>
        </li>
        <li class="mt-5">
          <%= link_to logout_path, data: { turbo_method: :delete } do %>
            <i class="fa-solid fa-right-from-bracket"></i>
            <%= t('menu.logout') %>
          <% end %>
        </li>
      <% else %>
        <li>
          <%= link_to login_path do %>
          <i class="fa-solid fa-right-to-bracket"></i>
          <%= t('menu.login') %>
        <% end %>
        </li>
        <li>
          <%= link_to new_users_path do %>
            <i class="fa-solid fa-user-plus"></i>
            <%= t('menu.sign_up') %>
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_next_page.html.erb
<%= turbo_frame_tag "#{turbo_frame_id}-page-#{pagy.next}",  loading: :lazy, src: pagy_url_for(pagy, pagy.next) if pagy.next.present? %>

app/views/shared/_post_card.html.erb
<div id="card" class="border rounded-lg shadow-lg h-auto group transform hover:-translate-y-2 duration-200 bg-slate-50" >
  <div id="header" class="flex justify-between p-2 bg-slate-100 font-bold rounded-t-lg">
    <%= post_card.user.name %>
    <p><%= l post_card.created_at %></p>
  </div>
  <div id="contents" class="flex flex-col">
    <div id="main-image" class="relative overflow-hidden">
      <%= link_to image_tag(main_image_existence(post_card), class: 'h-auto w-full object-contain cursor-pointer transition-transform group-hover:scale-110 duration-200'), post_path(post_card.id), data: { turbo_frame: "_top" } %>
    </div>
    <div id="brand" class="p-1 min-h-10">
      <% brand_remove_duplicate(post_card.id).each do |brand| %>
        <%= link_to brand, posts_path(q: { gadgets_brand_cont: brand }), class: "badge bg-slate-200 hover:bg-slate-300" %>
      <% end %>
    </div>
  </div>
  <div id="footer" class="flex justify-end gap-2">
    <%= render 'posts/likes/like', post: post_card %>
    <div class="flex items-center gap-1 mr-2">
      <i class="fa-regular fa-comment"></i>
      <%= post_card.comments.count %>
    </div>
  </div>
</div>

app/views/shared/_post_grid.html.erb
<div class="grid grid-cols-1 px-4 gap-3 pb-3 md:grid-cols-3" >
  <%= render partial: 'shared/post_card', collection: posts %>
</div>
<%= render 'shared/next_page', { pagy: pagy, turbo_frame_id: turbo_frame_id } %>

app/views/shared/_search.html.erb
<div class="flex justify-center">
  <button class="my-5 text-xl bg-slate-50" onclick="my_modal_3.showModal()">
    <i class="fa-solid fa-magnifying-glass"></i>
    <%= t('defaults.search') %>
  </button>
  <dialog id="my_modal_3" class="modal">
    <div class="modal-box h-auto">
      <form method="dialog">
        <button class="btn btn-sm btn-circle btn-ghost absolute right-2 top-2">✕</button>
      </form>
      <%= search_form_for @q, url: url do |f| %>
        <div class="flex flex-col gap-5 mt-5">
          <div class="">
            <%= f.label t('search.genre') %>
            <%= f.select :gadgets_genre_name_eq, Genre.all.map{|genre|genre.name}, prompt: '指定なし', class: "form-controll border" %>
          </div>
          <div class="w-full" data-controller="autocomplete" data-autocomplete-url-value="/autocomplete/brand", role="combobox">
            <%= f.label t('search.brand') %>
            <%= f.search_field :gadgets_brand_cont, data: { autocomplete_target: 'input' }, class: 'form-controll base-form-area w-full max-w-xs', placeholder: '検索ワード' %>
            <%= f.hidden_field :content, data: { autocomplete_target: 'hidden' } %>
            <ul class="list-group bg-white absolute w-full md:text-sm max-w-max z-50 cursor-pointer" data-autocomplete-target="results"></ul>
          </div>
          <div class="w-full" data-controller="autocomplete" data-autocomplete-url-value="/autocomplete/name", role="combobox">
            <%= f.label t('search.name'), class: "mr-4" %>
            <%= f.search_field :gadgets_name_cont, data: { autocomplete_target: 'input'}, class: 'form-controll base-form-area w-full max-w-xs', placeholder: '検索ワード' %>
            <%= f.hidden_field :content, data: { autocomplete_target: 'hidden' } %>
            <ul class="list-group bg-white absolute w-full md:text-sm max-w-max z-50 cursor-pointer" data-autocomplete-target="results"></ul>
          </div>
          <div class="flex justify-center">
            <%= f.submit t('defaults.search'), class: 'base-btn w-20' %>
          </div>
        </div>
      <% end %>
    </div>
  </dialog>
</div>