config/routes.rb
Rails.application.routes.draw do
  root 'tops#index'

  resource :tops, only: [] do
    collection do
      get 'terms_of_service'
      get 'privacy_policy'
    end
  end

  resource :users, only: %i[new create show edit update]

  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'

  post "oauth/callback", to: "oauths#callback"
  get "oauth/callback", to: "oauths#callback"
  get "oauth/:provider", to: "oauths#oauth", as: :auth_at_provider

  resource :my_page, only: [] do
    collection do
      get 'home', as: ''
      get 'liked'
      get 'my_posts'
    end
  end

  resources :password_resets, only: %i[ new create edit update ] do
    collection do
      get 'sended_mail'
      get 'after_setting'
    end
  end

  resources :posts do
    resource :likes, only: %i[ create destroy ]
    resources :likes, only: %i[ index ]
    resources :comments
    collection do
      get 'ranking'
      get 'rakuten_search'
    end
  end

  resources :gadgets do
    collection do
      get 'ranking'
    end
  end

  resources :autocomplete do
    collection do
      get :brand
      get :name
    end
  end

  resources :my_desks do
    member do
      post 'add_gadget'
      delete 'remove_gadget'
    end
  end

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
end

app/models/my_desk.rb
class MyDesk < ApplicationRecord
  has_many :my_desk_gadgets, dependent: :destroy
  has_many :gadgets, through: :my_desk_gadgets

  belongs_to :user

  validates :name, presence: true
end

app/controllers/my_desks_controller.rb
class MyDesksController < ApplicationController
  before_action :set_my_desk, only: %i[show edit update destroy add_gadget remove_gadget]
  before_action :set_gadget, only: %i[add_gadget remove_gadget]

  def index
    @my_desks = current_user.my_desks
    @default_my_desk = current_user.my_desks.first
    @default_my_desk_gadgets = current_user.my_desks.first.gadgets
  end

  def show
    @gadgets = @my_desk.gadgets.order(created_at: :desc)
  end

  def new
    @my_desk = MyDesk.new
  end

  def edit
  end

  def create
    @my_desk = current_user.my_desks.new(my_desk_params)
    respond_to do |format|
      if @my_desk.save
        format.turbo_stream
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @my_desk.update(my_desk_params)
        format.turbo_stream
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @my_desk.destroy!
    respond_to do |format|
      format.turbo_stream
    end
  end

  def add_gadget
    respond_to do |format|
      format.turbo_stream do
        if @my_desk.my_desk_gadgets.find_by(gadget_id: @gadget.id).present?
          flash.now[:error] = t('.registered', my_desk_name: @my_desk.name)
        elsif @my_desk.gadgets << @gadget
          flash.now[:success] = t('.new_register', my_desk_name: @my_desk.name)
        else
          flash.now[:error] = t('.fail')
        end
        render turbo_stream: turbo_stream.prepend('flash_messages', partial: 'shared/flash_message', locals: flash)
      end
    end
  end

  def remove_gadget
    my_desk_gadget = @my_desk.my_desk_gadgets.find_by(gadget_id: @gadget)

    return unless my_desk_gadget.destroy!

    respond_to do |format|
      format.turbo_stream
    end
  end

  private

  def set_my_desk
    @my_desk = MyDesk.find(params[:id])
  end

  def set_gadget
    @gadget = Gadget.find(params[:gadget_id])
  end

  def my_desk_params
    params.require(:my_desk).permit(:name, :user_id)
  end
end

app/helpers/my_desks_helper.rb
module MyDesksHelper
  def my_desk_gadgets_present?(mydesk, gadget)
    if gadget.present?
      render 'gadget', my_desk: mydesk, gadgets: gadget
    else
      render 'no_gadget'
    end
  end
end

app/views/my_desks/_form.html.erb
<%= form_with model: @my_desk, local: false do |f| %>
  <%= f.text_field :name, class: "base-form-area w-full" %>
  <%= f.submit class: "base-btn" %>
<% end %>

app/views/my_desks/_gadget.html.erb
<div class="grid grid-cols-2 md:grid-cols-4 gap-3 px-2">
  <% gadgets.each do |gadget| %>
    <%= turbo_frame_tag dom_id(gadget) do %>
      <div id="gadget-card" class="flex flex-col bg-white shadow rounded-lg text-base p-4">
        <div class="flex justify-end">
          <%= link_to remove_gadget_my_desk_path(my_desk, gadget_id: gadget.id), data: { turbo_method: :delete } do %>
            <i class="fa-solid fa-circle-xmark hover:text-blue-500 active:text-blue-700 transition hover:rotate-180"></i>
          <% end %>
        </div>
        <% if gadget.brand.present? %>
          <p class="badge bg-slate-200 min-h-6"><%= gadget.brand %></p>
        <% else %>
          <div class="min-h-6"></div>
        <% end %>
        <div class="flex justify-center py-2">
          <%= image_tag gadget.image_url, class: "shadow h-24 w-32 object-contain" %>
        </div>
        <div class="flex flex-col h-full">
          <%= link_to truncate_name(gadget.name), gadget_path(gadget), data: { turbo_frame: "modal_frame" }, class: "modal-trigger text-center p-2 h-full hover:text-blue-500" %>
          <div class="flex justify-end">
            <p class="badge bg-slate-200 text-sm"><%= gadget.genre.name %></p>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/my_desks/_my_desk.html.erb
<%= turbo_frame_tag dom_id(my_desk) do %>
  <li class="border-b shadow">
    <div class="flex p-0">
      <%= link_to my_desk.name, my_desk_path(my_desk.id), data: { turbo_frame: "my-desk-content" }, class: "w-full block hover:text-blue-500 p-2" %>
      <div class="dropdown dropdown-bottom md:dropdown-right p-2">
        <div tabindex="0" role="button" class="hover:text-blue-500">
          <i class="fa-solid fa-ellipsis"></i>
        </div>
        <ul tabindex="0" class="dropdown-content z-[1] menu p-1 shadow rounded-box w-20 md:w-32">
          <li>
            <%= link_to t('.edit'), edit_my_desk_path(my_desk) %>
          </li>
          <% unless current_user.my_desks.count == 1 %>
            <li>
              <%= link_to t('.destroy'), my_desk_path(my_desk), data: { turbo_method: :delete, turbo_confirm: t('.delete_confirmation') } %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </li>
<% end %>

app/views/my_desks/_no_gadget.html.erb
<div class="bg-slate-300 flex items-center justify-center gap-3 text-white text-lg px-5 py-14 my-14 rounded-xl">
  <i class="fa-solid fa-circle-exclamation text-white"></i>
  <p>登録されているアイテムがまだありません。</p>
</div>

app/views/my_desks/create.turbo_stream.erb
<%= turbo_stream.append "my_desks", partial: 'my_desks/my_desk', locals: { my_desk: @my_desk } %>
<%= turbo_stream.update MyDesk.new, "" %>

app/views/my_desks/destroy.turbo_stream.erb
<%= turbo_stream.remove dom_id(@my_desk) %>

app/views/my_desks/edit.html.erb
<%= turbo_frame_tag dom_id(@my_desk) do %>
  <%= render 'form' %>
<% end %>

app/views/my_desks/index.html.erb
<%= turbo_frame_tag "content" do %>
  <div class="flex flex-col items-center gap-1 w-full">
    <ul class="menu rounded-box w-2/3 md:w-2/5">
      <li>
        <details>
          <summary class="shadow">マイデスク選択</summary>
          <ul>
            <%= turbo_frame_tag "my_desks" do %>
              <% @my_desks.each do |my_desk| %>
                <%= render 'my_desk', my_desk: my_desk %>
              <% end %>
            <% end %>
            <li class="shadow bg-slate-50">
              <%= link_to "＋", new_my_desk_path, data: { turbo_frame: "new_my_desk" }, class: "hover:text-blue-500" %>
            </li>
            <%= turbo_frame_tag "new_my_desk" %>
          </ul>
        </details>
      </li>
    </ul>

    <%= turbo_frame_tag "my-desk-content" do %>
      <%= my_desk_gadgets_present?(@default_my_desk, @default_my_desk_gadgets) %>
    <% end %>
  </div>
<% end %>

app/views/my_desks/new.html.erb
<%= turbo_frame_tag "new_my_desk" do %>
  <%= render 'form' %>
<% end %>

app/views/my_desks/remove_gadget.turbo_stream.erb
<%= turbo_stream.remove dom_id(@gadget) %>

app/views/my_desks/show.html.erb
<%= turbo_frame_tag "my-desk-content" do %>
  <%= my_desk_gadgets_present?(@my_desk, @gadgets) %>
<% end %>

app/views/my_desks/update.turbo_stream.erb
<%= turbo_stream.replace dom_id(@my_desk), partial: 'my_desks/my_desk', locals: { my_desk: @my_desk } %>